### PR TITLE
Try to publish to ghcr.io ("GitHub Container Registry")

### LINKED ISSUE #10: Publish with Docker GitHub Action
See https://www.docker.com/blog/first-docker-github-action-is-here/ for details

### PR DESCRIPTION
**Pull request by koppor**
Fixes #10

### CODE REVIEW

**Comment by splitt3r** [comment]
Hey @koppor, thanks for the quick implementation 👍🏻 maybe you already googled / fixed it. The build failure could be related to the feature beeing opt in only for now: https://github.com/docker/build-push-action/issues/205#issuecomment-728894085. Anyway great work,

**Comment by koppor** [comment]
@splitt3r Thank you for the pointer. I also found it. I enabled it for my profile and for the dante-ev organization.

The last lines of the error message read as follows:

```
#19 pushing manifest for docker.io/danteev/texlive:latest
#19 pushing manifest for docker.io/danteev/texlive:latest 0.6s done
#19 pushing layers 0.3s done
#19 ERROR: unexpected status: 403 Forbidden
```

The image at dockerhub is publishes successfully (I checked https://hub.docker.com/repository/registry-1.docker.io/danteev/texlive/tags?ref=login&page=1&ordering=last_updated).

Need to trigger a build again; maybe it works.

**Comment by koppor** [comment]
Found the issue for the authoentication. It is `dante-ev`, not `danteev` (as in DockerHub).

**Comment by koppor** [comment]
Now, I am blocked by https://github.com/docker/build-push-action/issues/251.

I will merge nevertheless and hope the transfer of large images will be fixed some day.

**Comment by splitt3r** [comment]
I think you still need to make the image public.

**Comment by koppor** [comment]
For reference: The workflow is:

1. Ensure correct orga settings
2. First publish package (before, it is not available in the package list https://github.com/orgs/dante-ev/packages/)
3. Then, the package is available (https://github.com/orgs/dante-ev/packages/container/texlive/settings)
4. Make the package public

Fixed.

**Pull request merged**
